### ISSUE TITLE
Tryb wsadowy i dokumentacja

### ISSUE THREAD

**Issue by rantnar** [rantnar/p1-zs1-gr4#12]
Program ma funkcjonować w trybie wsadowym, przetwarzając dane z pliku, którego format jest ustalony przez użytkownika.

- [x] Program poprawnie czyta i przetwarza dane z pliku.
- [x] Program obsługuje błędy związane z czytaniem pliku (np. nieprawidłowy format, brak pliku).

**Comment by rantnar** [comment]
Program czyta i przetwarza dane z pliku.

**Comment by rantnar** [comment]
Trzeba dodać sprawdzanie by plik miał rozszerzenie czy plik ma rozszerzenie json

**Comment by keepitfoxy** [comment]
Program obsługuje błędy związane z czytaniem pliku (np. nieprawidłowy format, brak pliku).

**Comment by keepitfoxy** [comment]
Trzeba:

- [x] Niech run_batch_mode sprawdza, czy json, który został wczytany da się przetworzyć

- [x]  Niech sprawdza, czy ma wszystkie potrzebne klucze

- [x] Na razie odczytuje pliki tylko do poziomu folderu, w którym jest program. Spróbujmy jeszcze poszukać rozwiązania do odczytywania plików w innej części dysku bez wyrzucania błędu JSONDecodeError (próbowałam z dekodowaniem utf-8, ale cos nie wyszło)
